import { StyleSheet } from 'react-native';

// export const stylesCreate = StyleSheet.create({
//   container: {
//     flex: 1,
//     justifyContent: 'center',
//     alignItems: 'center',
//   },
//   joinButtonContainer: {
//     margin: 80,
//     backgroundColor: '#00BFFF',
//     height: 50,
//     justifyContent: 'center',
//     borderRadius: 10,
//     overflow: 'hidden',
//   },
//   createButtonContainer: {
//     margin: 80,
//     backgroundColor: '#40E0D0',
//     height: 50,
//     justifyContent: 'center',
//     borderRadius: 10,
//     overflow: 'hidden',
//   },
//   text: {
//     alignSelf: 'center',
//     fontWeight: 'bold',
//     fontSize: 30,
//     color: 'grey',
//   },
//   alternativeLayoutButtonContainer: {
//     margin: 20,
//     flexDirection: 'row',
//     justifyContent: 'space-between',
//   },
// });
//
// export const stylesRoom = StyleSheet.create({
//   container: {
//     flex: 1,
//     justifyContent: 'center',
//     alignItems: 'center',
//   },
//   buttonContainer: {
//     margin: 80,
//     backgroundColor: '#00BFFF',
//     height: 40,
//     justifyContent: 'center',
//     width: 100,
//     borderRadius: 10,
//     overflow: 'hidden',
//     alignItems: 'stretch',
//   },
//   alternativeLayoutButtonContainer: {
//     margin: 20,
//     flexDirection: 'row',
//     justifyContent: 'space-between',
//   },
//   textEnter: {
//     height: 40,
//     width: '70%',
//     margin: 20,
//     marginTop: 80,
//     padding: 10,
//     borderColor: '#40E0D0',
//     borderWidth: 1,
//     backgroundColor: 'white',
//   },
//   pickerContainer: {
//     flex: 1,
//     flexDirection: 'row',
//     alignItems: 'center',
//   },
//   twoPickers: {
//     width: 30,
//     height: 80,
//     marginLeft: 20,
//     borderColor: '#40E0D0',
//     borderWidth: 1,
//     justifyContent: 'center',
//     alignItems: 'center',
//   },
//   twoPickerItems: {
//     height: '95%',
//     width: '90%',
//     color: 'black',
//     backgroundColor: 'white',
//     borderColor: '#40E0D0',
//     fontSize: 16,
//   },
//   text: {
//     // alignSelf: 'center',
//     // fontWeight: 'bold',
//     fontSize: 16,
//   },
// });
// export const stylesRoomCode = StyleSheet.create({
//   container: {
//     flex: 1,
//     justifyContent: 'center',
//     alignItems: 'center',
//   },
//   buttonContainer: {
//     margin: 80,
//     backgroundColor: '#00BFFF',
//     height: 40,
//     justifyContent: 'center',
//     width: 120,
//     borderRadius: 10,
//     overflow: 'hidden',
//     alignItems: 'stretch',
//   },
//   welcome: {
//     fontSize: 18,
//     fontWeight: 'bold',
//     textAlign: 'center',
//   },
//   alternativeLayoutButtonContainer: {
//     margin: 20,
//     flexDirection: 'row',
//     justifyContent: 'space-between',
//   },
//   textEnter: {
//     height: 40,
//     width: 100,
//     margin: 20,
//     padding: 10,
//     borderColor: 'gray',
//     borderWidth: 1,
//   },
//   text: {
//     alignSelf: 'center',
//     fontWeight: 'bold',
//     fontSize: 30,
//     color: 'grey',
//   },
// });
// export const stylesHome = StyleSheet.create({
//   container: {
//     flex: 4,
//   },
//   sketch: {
//     flex: 1,
//     borderColor: '#40E0D0',
//     borderWidth: 3,
//     backgroundColor: 'white',
//   },
//   sketchContainer: {
//     padding: 20,
//     height: '100%',
//     width: '100%',
//   },
//   image: {
//     flex: 1,
//   },
//   label: {
//     width: '100%',
//     padding: 5,
//     alignItems: 'center',
//   },
//   buttonContainer: {
//     flex: 1,
//     flexDirection: 'row',
//     justifyContent: 'space-around',
//     margin: 0,
//   },
//   undoButton: {
//     zIndex: 1,
//     width: 70,
//     height: 40,
//     marginBottom: 10,
//     alignSelf: 'center',
//     backgroundColor: '#CD5C5C',
//     justifyContent: 'center',
//     borderRadius: 10,
//     overflow: 'hidden',
//   },
//   saveButton: {
//     zIndex: 1,
//     width: 70,
//     height: 40,
//     marginBottom: 10,
//     alignSelf: 'center',
//     backgroundColor: '#40E0D0',
//     justifyContent: 'center',
//     borderRadius: 10,
//     overflow: 'hidden',
//   },
//   text: {
//     alignSelf: 'center',
//     fontWeight: 'bold',
//     fontSize: 18,
//   },
// });
//
// export const stylesWaiting = StyleSheet.create({
//   container: {
//     flex: 1,
//     justifyContent: 'center',
//     alignItems: 'center',
//     backgroundColor: '#D8BFD8',
//   },
//   alternativeLayoutButtonContainer: {
//     margin: 20,
//     flexDirection: 'row',
//     justifyContent: 'space-between',
//   },
//   buttonContainer: {
//     margin: 80,
//     backgroundColor: '#00BFFF',
//     height: 40,
//     justifyContent: 'center',
//     width: 120,
//     borderRadius: 10,
//     overflow: 'hidden',
//     alignItems: 'stretch',
//   },
// });
//
// export const stylesContest = StyleSheet.create({
//   container: {
//     flex: 1,
//     justifyContent: 'center',
//     alignItems: 'center',
//   },
//   buttonContainer: {
//     margin: 80,
//     backgroundColor: '#00BFFF',
//     height: 40,
//     justifyContent: 'center',
//     width: 120,
//     borderRadius: 10,
//     overflow: 'hidden',
//     alignItems: 'stretch',
//   },
//   alternativeLayoutButtonContainer: {
//     margin: 20,
//     flexDirection: 'row',
//     justifyContent: 'space-between',
//   },
// });
//
// export const stylesWinner = StyleSheet.create({
//   container: {
//     flex: 1,
//     justifyContent: 'center',
//     alignItems: 'center',
//   },
//   buttonContainer: {
//     margin: 80,
//     backgroundColor: '#00BFFF',
//     height: 40,
//     justifyContent: 'center',
//     width: 120,
//     borderRadius: 10,
//     overflow: 'hidden',
//     alignItems: 'stretch',
//   },
//   welcome: {
//     fontSize: 20,
//     textAlign: 'center',
//   },
//   alternativeLayoutButtonContainer: {
//     margin: 20,
//     flexDirection: 'row',
//     justifyContent: 'space-between',
//   },
//   textEnter: {
//     height: 40,
//     width: 100,
//     margin: 20,
//     padding: 10,
//     borderColor: 'gray',
//     borderWidth: 1,
//   },
// });

export const stylesDefault = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nonButtonContainer: {
    flex: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heading: {
    alignSelf: 'center',
    textAlign: 'center',
    fontWeight: 'bold',
    fontFamily: 'Avenir',
    fontSize: 40,
    color: '#00BFFF',
  },
  text: {
    alignSelf: 'center',
    fontWeight: 'bold',
    fontFamily: 'Avenir',
    fontSize: 20,
    color: 'cadetblue',
  },
  buttonText: {
    alignSelf: 'center',
    fontWeight: 'bold',
    fontFamily: 'Avenir',
    color: 'white',
  },
  button: {
    justifyContent: 'center',
    backgroundColor: '#00BFFF',
    padding: 10,
    height: 50,
    width: 120,
    borderRadius: 10,
    overflow: 'hidden',
  },
  buttonGroup: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-evenly',
    margin: 10,
  },
  pickerContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textEnter: {
    height: 40,
    width: '100%',
    margin: 5,
    padding: 10,
    borderColor: '#40E0D0',
    borderWidth: 1,
    backgroundColor: 'white',
  },
  twoPickers: {
    width: 40,
    height: 40,
    margin: 5,
    borderColor: '#40E0D0',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  twoPickerItems: {
    height: '90%',
    width: '90%',
    color: 'black',
    backgroundColor: 'white',
    borderColor: '#40E0D0',
    fontSize: 16,
  },
  heading2: {
    flex: 1,
    alignItems: 'center',
    textAlign: 'center',
    fontWeight: 'bold',
    fontFamily: 'Avenir',
    fontSize: 30,
    color: '#00BFFF',
  },
  textBkg: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'white',
    borderColor: '#40E0D0',
    borderWidth: 1,
  },
  sketch: {
    flex: 4,
    width: 275,
    height: 275,
    borderColor: '#40E0D0',
    borderWidth: 3,
    backgroundColor: 'white',
  },
  sketchContainer: {
    padding: 10,
    height: '100%',
    width: '100%',
  },
  undoButton: {
    justifyContent: 'center',
    padding: 10,
    height: 50,
    width: 120,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#CD5C5C',
  },
  saveButton: {
    justifyContent: 'center',
    padding: 10,
    height: 50,
    width: 120,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#40E0D0',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
  },
  image: {
    flex: 4,
    height: 200,
    width: 200,
  },
});
